name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pytest pytest-cov requests httpx

      - name: Run tests with coverage
        run: |
          pytest --cov=app --cov-report=xml

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Verify Java Installation
        run: |
          java -version  # Check the installed Java version

      - name: Install SonarScanner
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget
          
          # Download and install SonarScanner
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonar-scanner-cli-4.6.2.2472-linux.zip
          sudo mv sonar-scanner-4.6.2.2472-linux /opt/sonar-scanner
          
          # Add SonarScanner to PATH
          echo '/opt/sonar-scanner/bin' >> $GITHUB_PATH

      - name: Verify SonarScanner Installation
        run: |
          sonar-scanner --version  # Check SonarScanner version

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Use your SonarQube token
        run: |
          sonar-scanner \
            -Dsonar.projectKey=demo-jazzx \
            -Dsonar.sources=app \
            -Dsonar.tests=tests \
            -Dsonar.python.coverage.reportPaths=coverage.xml \
            -Dsonar.host.url=http://172.210.15.27:9000 \
            -Dsonar.login=$SONAR_TOKEN
