
name: CI

on:
  push:
    branches:
      - main  # Adjust to your main branch
  pull_request:
    branches:
      - main  # Adjust to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify your Python version

      - name: Install dependencies
        run: |
          pip install fastapi uvicorn pytest pytest-cov httpx

      - name: Install SonarQube Scanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-4.9.0.2152-linux.zip
          unzip sonar-scanner-4.9.0.2152-linux.zip
          sudo mv sonar-scanner-4.9.0.2152-linux /opt/sonar-scanner
          echo "/opt/sonar-scanner/bin" >> $GITHUB_PATH

      - name: Run tests with coverage
        run: |
          pytest --cov=app tests/

      - name: Prepare SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Store your SonarQube token in GitHub Secrets
        run: |
          sonar-scanner \
            -Dsonar.projectKey=demo-jazzx \
            -Dsonar.host.url=http://172.210.15.27:9000 \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.sources=app \
            -Dsonar.tests=tests \
            -Dsonar.language=py \
            -Dsonar.python.coverage.reportPaths=coverage.xml

      - name: Upload coverage results
        run: |
          pytest --cov=app --cov-report=xml
