
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pytest pytest-cov requests httpx

      - name: Run tests with coverage
        run: |
          pytest --cov=app --cov-report=xml

      - name: Install SonarScanner
        run: |
          curl -o sonar-scanner.zip -L https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/4.6.2.2472/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonar-scanner.zip -d sonar-scanner
          echo "${{ github.workspace }}/sonar-scanner/sonar-scanner-4.6.2.2472-linux/bin" >> $GITHUB_PATH

      - name: Run SonarScanner
        run: |
          sonar-scanner \
            -Dsonar.projectKey=demo-jazzx \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://172.210.15.27:9000 \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Upload coverage report to SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          curl -X POST -u $SONAR_TOKEN: \
            -F projectKey=demo-jazzx \
            -F file=@coverage.xml \
            http://172.210.15.27:9000/api/coverage/upload
