
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Update to v3 for Node 16 compatibility
      
      - name: Set up Python
        uses: actions/setup-python@v4  # Update to v4 for Node 16 compatibility
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pytest pytest-cov requests

      - name: Run tests with coverage
        run: |
          pytest --cov=app --cov-report=xml

      - name: Upload coverage report to SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          curl -X POST -u $SONAR_TOKEN: \
            -F projectKey=demo-jazzx \
            -F file=@coverage.xml \
            http://172.210.15.27:9000/api/coverage/upload
